import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const index=fs.readFileSync("index.html","utf8");
const sw=fs.readFileSync("sw.js","utf8");
const arp=fs.readFileSync("assets/evia-arp-v80.js","utf8");
const discussion=fs.readFileSync("assets/evia-arp-discussion-v82.js","utf8");
const practical=fs.readFileSync("assets/evia-arp-practical-v83.js","utf8");
const functional=fs.readFileSync("assets/evia-functional-skills-v194.js","utf8");
const live=fs.readFileSync("assets/evia-selfobs-live.js","utf8");
const state=fs.readFileSync("assets/evia-evidence-state-v204.js","utf8");
const targets=fs.readFileSync("assets/evia-targets.js","utf8");
const exportStatus=fs.readFileSync("assets/evia-export-status.js","utf8");
const staged=fs.readFileSync("assets/evia-staged-evidence-v202.js","utf8");
const manifest=JSON.parse(fs.readFileSync("update.json","utf8"));

function bank(){
  const match=functional.match(/const BANK=(\{.*\});\nlet layer=/s);
  assert.ok(match,"Functional Skills BANK must remain embedded");
  return JSON.parse(match[1]);
}

test("v209 is one clean runtime without obsolete patch layers",()=>{
  assert.equal(String(manifest.version),"209");
  assert.match(index,/evia-app-version" content="209"/);
  assert.match(index,/evia-version-v209\.js\?v=209/);
  assert.match(index,/evia-updater\.js\?v=209/);
  assert.match(sw,/evia-shell-v209/);
  assert.match(sw,/evia-version-v209\.js/);
  for(const path of [
    "assets/evia-arp-mock-only-v197.js",
    "assets/evia-recovery-v207.js",
    "assets/evia-functional-skills-v195.js",
    "assets/evia-functional-skills-v196.js",
    "assets/evia-evidence-state-v203.js",
  ]) assert.equal(fs.existsSync(path),false,`${path} must stay deleted`);
  assert.doesNotMatch(index,/evia-arp-mock-only-v197|evia-recovery-v207|evia-functional-skills-v195|evia-functional-skills-v196|evia-evidence-state-v203/);
  assert.doesNotMatch(sw,/evia-arp-mock-only-v197|evia-recovery-v207|evia-functional-skills-v195|evia-functional-skills-v196|evia-evidence-state-v203/);
});

test("Discussion is permanently Mock Discussion only",()=>{
  assert.match(discussion,/data-discussion-mode=\"mock\"/);
  assert.match(discussion,/Mock Discussion/);
  assert.doesNotMatch(discussion,/data-discussion-mode=\"learn\"|data-discussion-mode=\"practice\"/);
  assert.doesNotMatch(discussion,/MutationObserver/);
});

test("Practical is permanently Mock Practical only with camera and gallery",()=>{
  assert.match(practical,/data-practical-mode=\"mock\"/);
  assert.match(practical,/Mock Practical/);
  assert.doesNotMatch(practical,/data-practical-mode=\"learn\"|data-practical-mode=\"guided\"/);
  assert.match(practical,/capture=\"environment\" data-evidence-file/);
  assert.match(practical,/>Camera<\/span>/);
  assert.match(practical,/>Gallery<\/span>/);
  assert.doesNotMatch(practical,/MutationObserver/);
});

test("Maths and English are owned directly by the ARP home below Practical",()=>{
  const practicalAt=arp.indexOf('data-arp-option="practical"');
  const mathsAt=arp.indexOf('data-fs194-subject="maths"');
  const englishAt=arp.indexOf('data-fs194-subject="english"');
  assert.ok(practicalAt>=0&&mathsAt>practicalAt&&englishAt>mathsAt);
  assert.match(arp,/Maths Level 2/);
  assert.match(arp,/English Level 2/);
  assert.match(index,/evia-functional-skills-v194\.js\?v=209/);
  assert.doesNotMatch(functional,/MutationObserver|function patchRows\(/);
  assert.match(functional,/z-index:110000/);
});

test("Maths and English keep five equal five-question parts and Teach me",()=>{
  const data=bank();
  for(const subject of ["maths","english"]){
    assert.equal(data[subject].length,5,`${subject} must have five parts`);
    assert.equal(data[subject].flatMap(x=>x.questions).length,25,`${subject} must have 25 questions`);
    for(const part of data[subject])assert.equal(part.questions.length,5);
  }
  for(const q of Object.values(data).flatMap(parts=>parts.flatMap(x=>x.questions))){
    assert.equal(q.options.length,3);
    assert.ok(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<=2);
    assert.ok(String(q.explain||"").length>20);
  }
  assert.match(functional,/D · Teach me/);
  assert.match(functional,/data-fs194-teach/);
});

test("legacy KSB circles cannot be generated by the core tracker",()=>{
  assert.doesNotMatch(live,/<button data-code=\"\$\{c\}\"><b>\$\{c\}<\/b><span>/);
  assert.match(live,/<button data-code=\"\$\{c\}\"><b>\$\{c\}<\/b><\/button>/);
  assert.match(live,/<b>\$\{dots\(n\)\}<\/b>/,"original pale task tick must remain");
  assert.match(state,/LEGACY_MARKERS/);
  assert.match(state,/:scope > b\[class\]/);
  assert.doesNotMatch(state,/MutationObserver/);
  for(const source of ["learner","rpl","milos","witness"])assert.match(state,new RegExp(`evia-ksb-marker-v204 \\${source}|evia-ksb-marker-v204 \\$\\{type\\}`));
  assert.match(state,/background:#efc33d/);
  assert.match(state,/background:#7b3fc6/);
  assert.match(state,/background:#367fd0/);
  assert.match(state,/background:#d88b45/);
});

test("course-map failure has a direct recovery path",()=>{
  assert.match(live,/data-course-recover/);
  assert.match(live,/Choose course/);
  assert.match(live,/EviaCoursePacks/);
  assert.match(live,/\.manager/);
});

test("previous approved fixes remain intact",()=>{
  assert.match(targets,/EviaArpHomeScore\?\.progress\?\.\(\)/);
  assert.match(targets,/met:m\.epa\.pct>=t\.targetPct/);
  assert.match(exportStatus,/\[data-sign-download\]/);
  assert.match(exportStatus,/evia-export-progress-ring-v205/);
  assert.match(staged,/renderPhotoCanvasReview\(canvas,filePromise\)/);
});
